<a href="https://colab.research.google.com/github/Ajay7545/DeceptionDetection/blob/master/DeceptionDetectionTry1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import time
import numpy as np
import os
from keras import layers, models, callbacks, regularizers, optimizers
from keras.layers import advanced_activations
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler as ms
import pandas as pd
import numpy as np
import numpy
import csv
import pandas as pd
import matplotlib.pyplot as plt
import numpy
import matplotlib.pyplot as plt
import os
import glob
import datetime as dt

from datetime import timedelta
import numpy
import matplotlib.pyplot as plt
from pandas import read_csv
import pandas as pd
import math
from keras.callbacks import Callback
from keras.optimizers import adagrad, adam
from IPython.display import clear_output
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

Using TensorFlow backend.


In [3]:
df1=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_combine_123.csv")
df1.head()

time in sec        P7        P8        O1        O2  case
0            1  1.919887  2.501204  3.080694  2.074751     1
1            2  1.814434  0.909816  3.112040  0.501960     1
2            3  1.647871 -0.821347  3.006349 -1.381623     1
3            4  0.904148 -3.128725  2.175032 -3.619939     1
4            5 -0.180205 -5.614045  0.504864 -5.903103     1

In [0]:
df1=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_combine_1.csv")
df2=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_fam_1_filt_13.csv")
df3=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_non_1_filt_13.csv")
df4=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_combine_1.csv")
df5=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_fam_1_filt_13.csv")

df6=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_non_1_filt_13.csv")
df7=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_test_1.csv")
df8=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_combine_1.csv")
df9=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_combine_ica.csv")
df10=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_nn_1.csv")

df11=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_test_1.csv")
df12=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_test_ica.csv")
df13=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/murli_fam_2_filt_13.csv")
df14=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/murli_non_1_filt_13.csv")
df15=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_combine_1.csv")

df16=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_fam_1_filt_13.csv")
df17=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_non_2_filt_13.csv")
df18=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_test_1.csv")
df19=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_combine_1.csv")
df20=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_fam_1_filt_13.csv")

df21=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_non_1_filt_13.csv")
df22=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_combine_1.csv")
df23=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_fam_1_filt_13.csv")
df24=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_non_1_filt_13.csv")
df25=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_combine_1.csv")

df26=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_fam_1_filt_13.csv")
df27=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_non_1_filt_13.csv")
df28=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_combine_1.csv")
df29=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_fam_1_filt_13.csv")
df30=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_non_1_filt_13.csv")

df31=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sunny_fam_1_filt_13.csv")
df32=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sunny_non_1_filt_13.csv")
df33=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_combine_1.csv")
df34=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_fam_1_filt_13.csv")
df35=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_non_1_filt_13.csv")

df36=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_combine_1.csv")
df37=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_fam_1_filt_13.csv")
df38=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_non_1_filt_13.csv")
df39=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_combine_1.csv")
df40=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_fam_1_filt_13.csv")

df41=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_non_1_filt_13.csv")

In [0]:
data=df1.append(df2)
data=data.append(df3)
data=data.append(df4)
data=data.append(df5)
data=data.append(df6)
data=data.append(df7)
data=data.append(df8)
data=data.append(df9)
data=data.append(df10)
data=data.append(df11)
data=data.append(df12)
data=data.append(df13)
data=data.append(df14)
data=data.append(df15)
data=data.append(df16)
data=data.append(df17)
data=data.append(df18)
data=data.append(df19)
data=data.append(df20)
data=data.append(df21)
data=data.append(df22)
data=data.append(df23)
data=data.append(df24)
data=data.append(df25)
data=data.append(df26)
data=data.append(df27)
data=data.append(df28)
data=data.append(df29)
data=data.append(df30)
data=data.append(df31)
data=data.append(df32)
data=data.append(df33)
data=data.append(df34)
data=data.append(df35)
data=data.append(df36)
data=data.append(df37)
data=data.append(df38)
data=data.append(df39)
data=data.append(df40)
data=data.append(df41)
data.shape

In [0]:
de=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/emotions.csv")

In [0]:
df1.head(2)

time in sec        P7        P8        O1        O2  case
0            1  1.919887  2.501204  3.080694  2.074751     1
1            2  1.814434  0.909816  3.112040  0.501960     1

In [0]:
df2.head(2)
df4.head(2)
df4.rename({"Sample":"time in sec"},axis=1,inplace=True)
df4.head(2)

time in sec        P7        P8        O1        O2  case
0            1 -3.239991  2.845498  2.576851  5.817392     1
1            2 -3.647375  4.195437  2.032674  5.409704     1

In [0]:
df4.to_csv("data4.csv")

In [0]:
df5.head(2)
df6.head(2)
df6.rename({"Sample":"time in sec"},axis=1,inplace=True)
df6.head(2)

time in sec        P7        P8        O1        O2  case
0            1 -0.222316 -0.068399 -0.209128 -0.162353     0
1            2  0.361101  0.282927  0.431919  0.699698     0

In [0]:
df6.to_csv("data6.csv")

In [0]:
df7.head(2)

Sample        P7        P8        O1        O2  case
0       1  3.846958  3.689288  4.300865  3.229091     1
1       2  0.167942  2.067021  1.028694 -0.841279     1

In [0]:
df7.rename({"Sample":"time in sec"},axis=1,inplace=True)
df7.to_csv("data7.csv")
df7.head(2)

time in sec        P7        P8        O1        O2  case
0            1  3.846958  3.689288  4.300865  3.229091     1
1            2  0.167942  2.067021  1.028694 -0.841279     1

In [0]:
df8.head(2)

Sample        P7        P8        O1        O2  case
0       1  1.919887  2.501204  3.080694  2.074751     1
1       2  1.814434  0.909816  3.112040  0.501960     1

In [0]:
df8.rename({"Sample":"time in sec"},axis=1,inplace=True)
df8.to_csv("data8.csv")
df8.head(2)

time in sec        P7        P8        O1        O2  case
0            1  1.919887  2.501204  3.080694  2.074751     1
1            2  1.814434  0.909816  3.112040  0.501960     1

In [0]:
df9.rename({"Sample":"time in sec"},axis=1,inplace=True)
df9.to_csv("data9.csv")
df9.head(2)

time in sec        P7        P8        O1        O2  case
0            1 -0.000461  0.001127  0.000256  0.000017     1
1            2 -0.000131  0.001219  0.000345 -0.000784     1

In [0]:
df10.rename({"Sample":"time in sec"},axis=1,inplace=True)
df10.to_csv("data10.csv")
df10.head(2)

time in sec        P7        P8        O1        O2  case
0            1  3.478626  3.073398  6.011334  6.466850     0
1            2  3.979115  2.881399  5.301760  6.017831     0

In [0]:
df11.rename({"Sample":"time in sec"},axis=1,inplace=True)
df11.to_csv("data11.csv")
df11.head(2)

time in sec         P7         P8         O1         O2  case
0            1  22.442435  16.776875  22.315031  24.554244     1
1            2  17.360605  12.769806  20.395620  20.240154     1

In [0]:
df12.drop(['Unnamed: 0'],axis=1,inplace=True)
df12.rename({"Sample":"time in sec"},axis=1,inplace=True)
df12.to_csv("data12.csv")
df12.head(1)

time in sec        P7      P8        O1       O2  case
0            1  0.015003  0.0069 -0.006951 -0.00252     1

In [0]:
df18.rename({"Sample":"time in sec"},axis=1,inplace=True)
df18.to_csv("data18.csv")
df18.head(1)

time in sec        P7        P8        O1        O2  case
0            1  5.076048  2.035574  5.650254  3.482081     1

In [0]:
df19.rename({"Sample":"time in sec"},axis=1,inplace=True)
df19.to_csv("data19.csv")
df19.head(1)

time in sec        P7        P8       O1        O2  case
0            1  1.855429  3.721328  0.76468  0.130835     1

In [0]:
df21.rename({"Sample":"time in sec"},axis=1,inplace=True)
df21.to_csv("data21.csv")
df21.head(1)

time in sec        P7        P8       O1        O2  case
0            1  0.260619  0.267886  0.15431  0.174198     0

In [0]:
df22.rename({"Sample":"time in sec"},axis=1,inplace=True)
df22.to_csv("data22.csv")
df22.head(1)

time in sec        P7        P8        O1        O2  case
0            1 -7.609301 -4.738793 -4.828183 -6.883428     1

In [0]:
df24.rename({"Sample":"time in sec"},axis=1,inplace=True)
df24.to_csv("data24.csv")
df24.head(1)

time in sec        P7        P8        O1        O2  case
0            1 -0.029517 -0.040655 -0.017535 -0.013207     0

In [0]:
df25.rename({"Sample":"time in sec"},axis=1,inplace=True)
df25.to_csv("data25.csv")
df25.head(1)

time in sec        P7       P8        O1         O2  case
0            1  6.791923 -2.55749  11.31696  10.443311     1

In [0]:
df27.head(1)

Sample       P7        P8        O1        O2  case
0       1  1.23186  0.333497  1.281548  1.141624     0

In [0]:
df27.rename({"Sample":"time in sec"},axis=1,inplace=True)
df27.to_csv("data27.csv")
df27.head(1)

time in sec       P7        P8        O1        O2  case
0            1  1.23186  0.333497  1.281548  1.141624     0

In [0]:
df28.head(1)

Sample        P7        P8        O1        O2  case
0       1 -3.602665 -6.004532 -6.587911 -4.201767     1

In [0]:
df28.rename({"Sample":"time in sec"},axis=1,inplace=True)
df28.to_csv("data28.csv")
df28.head(1)

time in sec        P7        P8        O1        O2  case
0            1 -3.602665 -6.004532 -6.587911 -4.201767     1

In [0]:
df30.head(1)

Sample        P7        P8        O1        O2  case
0       1  0.200144 -0.022276  0.145727  0.234376     0

In [0]:
df29.rename({"Sample":"time in sec"},axis=1,inplace=True)
df29.to_csv("data29.csv")
df29.head(1)

time in sec        P7        P8        O1        O2  case
0            1  0.102475 -0.119854 -0.017485  0.206888     1

In [0]:
df30.head(1)

Sample        P7        P8        O1        O2  case
0       1  0.200144 -0.022276  0.145727  0.234376     0

In [0]:
df30.rename({"Sample":"time in sec"},axis=1,inplace=True)
df30.to_csv("data30.csv")
df30.head(1)

time in sec        P7        P8        O1        O2  case
0            1  0.200144 -0.022276  0.145727  0.234376     0

In [0]:
df32.head(1)

time in sec        P7        P8        O1        O2  case
0            1  1.094534 -0.695392  1.133272 -0.251647     0

In [0]:
df33.head(1)

Sample        P7        P8        O1       O2  case
0       1  5.854189  1.892939  1.089081  2.24739     1

In [0]:
df33.rename({"Sample":"time in sec"},axis=1,inplace=True)
df33.to_csv("data33.csv")
df33.head(1)

time in sec        P7        P8        O1       O2  case
0            1  5.854189  1.892939  1.089081  2.24739     1

In [0]:
df35.rename({"Sample":"time in sec"},axis=1,inplace=True)
df35.to_csv("data35.csv")
df35.head(1)

time in sec        P7        P8        O1        O2  case
0            1 -0.050948  0.028652 -0.068061 -0.050761     0

In [0]:
df36.head(1)

Sample        P7        P8        O1        O2  case
0       1  2.486292  3.728686 -2.560684 -6.129791     1

In [0]:
df36.rename({"Sample":"time in sec"},axis=1,inplace=True)
df36.to_csv("data36.csv")
df36.head(1)

time in sec        P7        P8        O1        O2  case
0            1  2.486292  3.728686 -2.560684 -6.129791     1

In [0]:
df38.rename({"Sample":"time in sec"},axis=1,inplace=True)
df38.to_csv("data38.csv")
df38.head(1)

time in sec        P7       P8        O1        O2  case
0            1 -0.142971 -0.12935 -0.039839 -0.007707     0

In [0]:
df39.head(1)

Sample        P7         P8        O1      O2  case
0       1 -3.602787 -11.840184 -1.659014 -1.3107     1

In [0]:
df39.rename({"Sample":"time in sec"},axis=1,inplace=True)
df39.to_csv("data39.csv")
df39.head(1)

time in sec        P7         P8        O1      O2  case
0            1 -3.602787 -11.840184 -1.659014 -1.3107     1

In [0]:
df41.rename({"Sample":"time in sec"},axis=1,inplace=True)
df41.to_csv("data41.csv")
df41.head(1)

time in sec        P7        P8       O1        O2  case
0            1 -0.325842  0.042877  0.00014 -0.000353     0

In [0]:
df1=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_combine_1.csv")
df2=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_fam_1_filt_13.csv")
df3=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_non_1_filt_13.csv")
df4=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data4.csv")
df5=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_fam_1_filt_13.csv")

df6=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data6.csv")
df7=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data7.csv")
df8=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data8.csv")
df9=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data9.csv")
df10=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data10.csv")

df11=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data11.csv")
df12=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data12.csv")
df13=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/murli_fam_2_filt_13.csv")
df14=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/murli_non_1_filt_13.csv")
df15=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_combine_1.csv")

df16=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_fam_1_filt_13.csv")
df17=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_non_2_filt_13.csv")
df18=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data18.csv")
df19=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data19.csv")
df20=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_fam_1_filt_13.csv")

df21=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data21.csv")
df22=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data22.csv")
df23=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_fam_1_filt_13.csv")
df24=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data24.csv")
df25=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data25.csv")

df26=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_fam_1_filt_13.csv")
df27=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data27.csv")
df28=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data28.csv")
df29=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data29.csv")
df30=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data30.csv")

df31=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sunny_fam_1_filt_13.csv")
df32=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sunny_non_1_filt_13.csv")
df33=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data33.csv")
df34=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_fam_1_filt_13.csv")
df35=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data35.csv")

df36=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data36.csv")
df37=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_fam_1_filt_13.csv")
df38=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data38.csv")
df39=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data39.csv")
df40=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_fam_1_filt_13.csv")

df41=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data41.csv")

In [6]:
#df1=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_combine_1.csv")
df2=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_fam_1_filt_13.csv")
df3=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_non_1_filt_13.csv")
data1=df2.append(df3)
#df4=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_combine_1.csv")
df5=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_fam_1_filt_13.csv")
df6=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_non_1_filt_13.csv")
data2=df5.append(df6)
#df7=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_test_1.csv")

#df8=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_combine_1.csv")
#df9=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_combine_ica.csv")
#df10=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_nn_1.csv")

#df11=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_test_1.csv")
#df12=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_test_ica.csv")
df13=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/murli_fam_2_filt_13.csv")
df14=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/murli_non_1_filt_13.csv")
data3=df13.append(df14)
#df15=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_combine_1.csv")
df16=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_fam_1_filt_13.csv")
df17=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_non_2_filt_13.csv")
data4=df16.append(df17)
#df18=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_test_1.csv")
#df19=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_combine_1.csv")

df20=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_fam_1_filt_13.csv")
df21=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_non_1_filt_13.csv")
data5=df20.append(df21)
#df22=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_combine_1.csv")
df23=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_fam_1_filt_13.csv")
df24=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_non_1_filt_13.csv")
data6=df23.append(df24)
#df25=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_combine_1.csv")
df26=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_fam_1_filt_13.csv")
df27=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_non_1_filt_13.csv")
data7=df26.append(df27)
#df28=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_combine_1.csv")
df29=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_fam_1_filt_13.csv")
df30=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_non_1_filt_13.csv")
data8=df29.append(df30)
df31=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sunny_fam_1_filt_13.csv")
df32=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sunny_non_1_filt_13.csv")
data9=df31.append(df32)
#df33=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_combine_1.csv")
df34=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_fam_1_filt_13.csv")
df35=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_non_1_filt_13.csv")
data10=df34.append(df35)
#df36=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_combine_1.csv")
df37=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_fam_1_filt_13.csv")
df38=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_non_1_filt_13.csv")
data11=df37.append(df38)
#df39=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_combine_1.csv")
df40=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_fam_1_filt_13.csv")
df41=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_non_1_filt_13.csv")
data12=df40.append(df41)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


In [7]:
data1.head(2)

time in sec        P7        P8        O1        O2  case
0            1  0.019579  0.031368  0.049292  0.031376     1
1            2 -0.005074  0.061788  0.172507 -0.009579     1

In [0]:
data1.drop(['time in sec'],axis=1,inplace=True)
data2.drop(['time in sec'],axis=1,inplace=True)
data3.drop(['time in sec'],axis=1,inplace=True)
data4.drop(['time in sec'],axis=1,inplace=True)
data5.drop(['time in sec'],axis=1,inplace=True)
data6.drop(['time in sec'],axis=1,inplace=True)
data7.drop(['time in sec'],axis=1,inplace=True)
data8.drop(['time in sec'],axis=1,inplace=True)
data9.drop(['time in sec'],axis=1,inplace=True)
data10.drop(['time in sec'],axis=1,inplace=True)
data11.drop(['time in sec'],axis=1,inplace=True)
data12.drop(['time in sec'],axis=1,inplace=True)


In [0]:
data1.head(2)

P7        P8        O1        O2  case
0  0.019579  0.031368  0.049292  0.031376     1
1 -0.005074  0.061788  0.172507 -0.009579     1

In [9]:
data1.shape

(27033, 5)

In [0]:
data1.to_csv('data1.csv')
data2.to_csv('data2.csv')
data3.to_csv('data3.csv')
data4.to_csv('data4.csv')
data5.to_csv('data5.csv')
data6.to_csv('data6.csv')
data7.to_csv('data7.csv')
data8.to_csv('data8.csv')
data9.to_csv('data9.csv')
data10.to_csv('data10.csv')
data11.to_csv('data11.csv')
data12.to_csv('data12.csv')

In [0]:
dfy=data1['case']

In [11]:
print(dfy.shape)
dfy.head(2)

(27033,)


0    1
1    1
Name: case, dtype: int64

In [12]:
dfx=data1.drop(['case'],axis=1)
dfx.head(1)

P7        P8        O1        O2
0  0.019579  0.031368  0.049292  0.031376

In [0]:
xtrain=dfx
ytrain=dfy

In [14]:
d1=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_combine_1.csv")
d1.head(1)

time in sec        P7        P8        O1        O2  case
0            1  1.919887  2.501204  3.080694  2.074751     1

In [15]:
d1=d1.drop(['time in sec'],axis=1)
d1.head(1)

P7        P8        O1        O2  case
0  1.919887  2.501204  3.080694  2.074751     1

In [0]:
yts=d1['case']

In [0]:
xts=d1.drop(['case'],axis=1)

In [0]:
ytest=yts
xtest=xts

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [0]:
#RandomForestRegressor(n_estimators=40, min_samples_leaf=3, max_features=0.5, n_jobs=-1, oob_score=True)
clf = RandomForestClassifier(n_estimators=300, max_depth=4,random_state=0)

In [0]:
clf.fit(xtrain, ytrain)

In [0]:
print(clf.feature_importances_)

[0.41194306 0.21220951 0.14780129 0.22804614]


In [0]:
xdata=clf.predict(xtest)
xdata2=clf.predict(xtrain)
xdata

array([1, 1, 1, ..., 0, 0, 0])

In [0]:

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
#confusion_matrix(xdata,ytest)

In [0]:
ctrain=confusion_matrix(xdata2,ytrain)
ctest=confusion_matrix(xdata,ytest)
print(ctrain) 
print(ctest)

[[6057 4479]
 [7467 9030]]
[[3536 2779]
 [4868 5610]]


In [0]:
c1,c2=confusion_matrix(xdata2,ytrain)
c3,c4=confusion_matrix(xdata,ytest)
tp,fp=c1
fn,tn=c2

tp1,fp1=c3
fn1,tn1=c4

print('accuracytrain:',(tp+tn)/(tp+fp+fn+tn))
print('accuracytest:',(tp1+tn1)/(tp1+fp1+fn1+tn1))

accuracytrain: 0.5580956608589501
accuracytest: 0.5446316917763354


trial Random...

In [0]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

In [24]:
clf = RandomForestClassifier(n_jobs=2 ,n_estimators=500, max_depth=4,random_state=0)
clf.fit(xtrain, ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=4, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [27]:
xtest.head(1)

P7        P8        O1        O2
0  1.919887  2.501204  3.080694  2.074751

In [30]:
xdata=clf.predict(xtest)
xdata

array([1, 1, 1, ..., 0, 0, 0])

In [32]:

ctest=confusion_matrix(xdata,ytest)
print(ctest)

[[3536 2779]
 [4868 5610]]


In [33]:
c1,c2=confusion_matrix(xdata,ytest)
tp,fp=c1
fn,tn=c2
print('accuracytest:',(tp+tn)/(tp+fp+fn+tn))

accuracytest: 0.5446316917763354


NEED TO CHECK FOR TRAINING AND TEST BOTH

In [0]:
data1.to_csv("d123.csv")

In [0]:
dff.drop(['Unnamed: 0','Unnamed: 0.1'],axis=1,inplace=True)
dff.head(4)

O1        O2        P7        P8  case  time in sec
0  3.080694  2.074751  1.919887  2.501204     1            1
1  3.112040  0.501960  1.814434  0.909816     1            2
2  3.006349 -1.381623  1.647871 -0.821347     1            3
3  2.175032 -3.619939  0.904148 -3.128725     1            4

In [0]:
dfy=dff['case']

In [0]:
dfx=dff.drop(['case'],axis=1)
dfx.head(2)

O1        O2        P7        P8  time in sec
0  3.080694  2.074751  1.919887  2.501204            1
1  3.112040  0.501960  1.814434  0.909816            2

In [0]:
dfx.shape

(919517, 5)

In [0]:
dfy.shape

(919517,)

In [0]:
xtrain=dfx[0:700000]
ytrain=dfy[0:700000]
xtest=dfx[700001:]
ytest=dfy[700001:]


In [0]:
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(700000, 5)
(700000,)
(219516, 5)
(219516,)




```
data for individual member
```



In [0]:
data1.shape

(27033, 5)

In [0]:
data1.head(1)

P7        P8        O1        O2  case
0  0.019579  0.031368  0.049292  0.031376     1

In [0]:
dfy=data1['case']

In [0]:
dfx=data1.drop(['case'],axis=1)

In [0]:
xtrain=dfx[0:20000]
ytrain=dfy[0:20000]
xtest=dfx[20001:]
ytest=dfy[20001:]


In [0]:
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(20000, 4)
(20000,)
(7032, 4)
(7032,)


1MODEL RANDOM ROREST CLASSIFIACTION TRY WITH ANY MODIFICATION IN DATASET


In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [0]:
#RandomForestRegressor(n_estimators=40, min_samples_leaf=3, max_features=0.5, n_jobs=-1, oob_score=True)
clf = RandomForestClassifier(n_estimators=500, max_depth=4,random_state=0)

In [0]:
clf.fit(xtrain, ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=4, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
print(clf.feature_importances_)

[0.47828549 0.13772456 0.1480042  0.23598575]


In [0]:
xdata=clf.predict(xtest)
xdata2=clf.predict(xtrain)
xdata

array([1, 1, 1, ..., 1, 1, 1])

In [0]:

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
#confusion_matrix(xdata,ytest)

In [0]:
ctrain=confusion_matrix(xdata2,ytrain)
ctest=confusion_matrix(xdata,ytest)
print(ctrain) 
print(ctest)

[[  198    34]
 [ 6293 13475]]
[[  69    0]
 [6963    0]]


In [0]:
c1,c2=confusion_matrix(xdata2,ytrain)
c3,c4=confusion_matrix(xdata,ytest)
tp,fp=c1
fn,tn=c2

tp1,fp1=c3
fn1,tn1=c4

print('accuracytrain:',(tp+tn)/(tp+fp+fn+tn))
print('accuracytest:',(tp1+tn1)/(tp1+fp1+fn1+tn1))

accuracytrain: 0.68365
accuracytest: 0.009812286689419795


In [0]:
clf = RandomForestClassifier(n_estimators=250, max_depth=60,random_state=1)
clf.fit(xtrain, ytrain)
xdata1=clf.predict(xtest)


In [0]:
xdata1.shape

(6792,)

In [0]:
xdata1.reshape(6792,1)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [0]:
xdata2=clf.predict(xtrain)
print(xdata2.shape)
xdata2.reshape(10000,1)

(10000,)


array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [0]:
confusion_matrix(xdata1,ytrain)

In [0]:
#clf = RandomForestClassifier(n_estimators=250, max_depth=60,random_state=1)
#clf.fit(xtrain, ytrain)
#xdata1=clf.predict(xtest)
#xdata2=clf.predict(xtrain)
p,r=confusion_matrix(xdata1,ytrain)
p1,r1=confusion_matrix(xdata2,ytest)
tp,fp=p
fn,tn=r

tp1,fp1=p1
fn1,tn1=r1
print(p,'\n',r,'\n')
print(p1,'\n',r1,'\n')
print('accuracytrain:',(tp+tn)/(tp+fp+fn+tn))
print('accuracytest:',(tp1+tn1)/(tp1+fp1+fn1+tn1))

In [0]:
df1=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_combine_1.csv")
df2=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_fam_1_filt_13.csv")
df3=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/alwyn_non_1_filt_13.csv")
df4=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_combine_1.csv")
df5=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_fam_1_filt_13.csv")

df6=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_non_1_filt_13.csv")
df7=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/deepak_test_1.csv")
df8=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_combine_1.csv")
df9=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_combine_ica.csv")
df10=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_nn_1.csv")

df11=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_test_1.csv")
df12=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/data12.csv")
df13=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/murli_fam_2_filt_13.csv")
df14=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/murli_non_1_filt_13.csv")
df15=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_combine_1.csv")

df16=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_fam_1_filt_13.csv")
df17=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_non_2_filt_13.csv")
df18=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/neeraj_test_1.csv")
df19=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_combine_1.csv")
df20=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_fam_1_filt_13.csv")

df21=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/nikhil_non_1_filt_13.csv")
df22=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_combine_1.csv")
df23=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_fam_1_filt_13.csv")
df24=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rahul_non_1_filt_13.csv")
df25=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_combine_1.csv")

df26=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_fam_1_filt_13.csv")
df27=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/rakesh_non_1_filt_13.csv")
df28=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_combine_1.csv")
df29=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_fam_1_filt_13.csv")
df30=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/subham_non_1_filt_13.csv")

df31=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sunny_fam_1_filt_13.csv")
df32=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sunny_non_1_filt_13.csv")
df33=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_combine_1.csv")
df34=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_fam_1_filt_13.csv")
df35=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/sus_non_1_filt_13.csv")

df36=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_combine_1.csv")
df37=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_fam_1_filt_13.csv")
df38=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/utkarsh_non_1_filt_13.csv")
df39=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_combine_1.csv")
df40=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_fam_1_filt_13.csv")

df41=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/vageesh_non_1_filt_13.csv")

In [0]:
dss=pd.read_csv("/content/drive/My Drive/COLAB Files/ddata/main_test_ica.csv")
dsa=dss.drop(["Unnamed: 0"],axis=1)
#dsa.to_csv("data12.csv")

In [0]:
data=df1.append(df2)
data=data.append(df3)
data=data.append(df4)
data=data.append(df5)
data=data.append(df6)
data=data.append(df7)
data=data.append(df8)
data=data.append(df9)
data=data.append(df10)
data=data.append(df11)
data=data.append(df12)
data=data.append(df13)
data=data.append(df14)
data=data.append(df15)
data=data.append(df16)
data=data.append(df17)
data=data.append(df18)
data=data.append(df19)
data=data.append(df20)
data=data.append(df21)
data=data.append(df22)
data=data.append(df23)
data=data.append(df24)
data=data.append(df25)
data=data.append(df26)
data=data.append(df27)
data=data.append(df28)
data=data.append(df29)
data=data.append(df30)
data=data.append(df31)
data=data.append(df32)
data=data.append(df33)
data=data.append(df34)
data=data.append(df35)
data=data.append(df36)
data=data.append(df37)
data=data.append(df38)
data=data.append(df39)
data=data.append(df40)
data=data.append(df41)
data.shape

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


(919517, 8)

In [0]:
data.to_csv("alldata.csv")

In [0]:
#data=data.append(df3)
df12.head(2)


In [0]:
df41.head(5)

Sample         P7         P8        O1        O2  case
0       1  -0.325842   0.042877  0.000140 -0.000353     0
1       2  -1.371003  -0.413019  0.129080  0.100299     0
2       3  -6.873812  -5.941464  0.865190  0.614402     0
3       4 -24.776830 -23.203765  2.858715  1.920402     0
4       5 -54.345455 -49.010572  5.974042  3.947546     0

In [0]:
datam=data

In [0]:
datam.head(2)

O1        O2        P7  ...  Unnamed: 0  case  time in sec
0  3.080694  2.074751  1.919887  ...         NaN     1          1.0
1  3.112040  0.501960  1.814434  ...         NaN     1          2.0

[2 rows x 8 columns]

In [0]:
datam.columns

Index(['O1', 'O2', 'P7', 'P8', 'Sample', 'Unnamed: 0', 'case', 'time in sec'], dtype='object')

skip below code i tried this for checking


In [0]:
datam.dropna

<bound method DataFrame.dropna of              O1        O2         P7  ...  Unnamed: 0  case  time in sec
0      3.080694  2.074751   1.919887  ...         NaN     1          1.0
1      3.112040  0.501960   1.814434  ...         NaN     1          2.0
2      3.006349 -1.381623   1.647871  ...         NaN     1          3.0
3      2.175032 -3.619939   0.904148  ...         NaN     1          4.0
4      0.504864 -5.903103  -0.180205  ...         NaN     1          5.0
5     -1.053419 -7.378522  -0.677102  ...         NaN     1          6.0
6     -1.446439 -7.311269   0.024599  ...         NaN     1          7.0
7     -0.995671 -6.185621   1.159475  ...         NaN     1          8.0
8     -0.743569 -5.049712   1.671114  ...         NaN     1          9.0
9     -0.617039 -3.870744   1.866702  ...         NaN     1         10.0
10     0.076222 -2.177234   2.450730  ...         NaN     1         11.0
11     1.495961 -0.052094   3.428284  ...         NaN     1         12.0
12     3.031046  

In [0]:
datam.columns

Index(['O1', 'O2', 'P7', 'P8', 'Sample', 'Unnamed: 0', 'case', 'time in sec'], dtype='object')

In [0]:
datam.drop(['Sample','Unnamed: 0'],axis=1,inplace=True)

In [0]:
datam.columns

Index(['O1', 'O2', 'P7', 'P8', 'case', 'time in sec'], dtype='object')

In [0]:
datam.head(2)

O1        O2        P7        P8  case  time in sec
0  3.080694  2.074751  1.919887  2.501204     1          1.0
1  3.112040  0.501960  1.814434  0.909816     1          2.0

In [0]:
datam.to_csv("datacombine.csv")

In [0]:
datam

In [0]:
datam.head(1)

O1        O2        P7        P8  case  time in sec
0  3.080694  2.074751  1.919887  2.501204     1          1.0

EMOTIONS

TRIALLL
PRE PROCESSING AND
MODELS

In [0]:
de.head(2)

# mean_0_a  mean_1_a  mean_2_a  ...  fft_748_b  fft_749_b     label
0        4.62      30.3    -356.0  ...     -162.0     280.00  NEGATIVE
1       28.80      33.1      32.0  ...      -31.6       2.57   NEUTRAL

[2 rows x 2549 columns]

In [0]:
de.shape

(2132, 2549)

In [0]:
ydata=de['label']

In [0]:
ydata.head(2)

0    NEGATIVE
1     NEUTRAL
Name: label, dtype: object

In [0]:
xdata=de.drop(['label'],axis=1)

In [0]:
xdata.head(2)

# mean_0_a  mean_1_a  mean_2_a  ...  fft_747_b  fft_748_b  fft_749_b
0        4.62      30.3    -356.0  ...     -162.0     -162.0     280.00
1       28.80      33.1      32.0  ...      -31.6      -31.6       2.57

[2 rows x 2548 columns]

In [0]:
print(xdata.shape)
print(ydata.shape)

(2132, 2548)
(2132,)


In [0]:
xtrain=xdata[0:1500]
ytrain=ydata[0:1500]
xtest=xdata[1501:]
ytest=ydata[1501:]


In [0]:
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(1500, 2548)
(1500,)
(631, 2548)
(631,)


In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [0]:
clf = RandomForestClassifier(n_estimators=250, max_depth=60,random_state=1)
clf.fit(xtrain, ytrain)
xdata1=clf.predict(xtest)
xdata2=clf.predict(xtrain)
p,r=confusion_matrix(xdata1,ytest)
p1,r1=confusion_matrix(xdata2,ytrain)
tp,fp=p
fn,tn=r

tp1,fp1=p1
fn1,tn1=r1
print(p,'\n',r,'\n')
print(p1,'\n',r1,'\n')
print('accuracytrain:',(tp+tn)/(tp+fp+fn+tn))
print('accuracytest:',(tp1+tn1)/(tp1+fp1+fn1+tn1))


In [0]:
clf = RandomForestClassifier(n_estimators=250, max_depth=60,random_state=1)


In [0]:
clf.fit(xtrain, ytrain)
xdata1=clf.predict(xtest)
xdata2=clf.predict(xtrain)


In [0]:
a1,a2,a3=confusion_matrix(xdata1,ytest)

In [0]:
b1,b2,b3=confusion_matrix(xdata2,ytrain)


In [0]:
a11,a12,a13=a1
a21,a22,a23=a2
a31,a32,a33=a3

In [0]:
b11,b12,b13=b1
b21,b22,b23=b2
b31,b32,b33=b3

In [0]:

print(a1,'\n',a2,'\n',a3,'\n')
print(b1,'\n',b2,'\n',b3,'\n')
print('accuracytest:',(a11+a22+a33)/(a11+a12+a13+a21+a22+a23+a31+a32+a33))
print('accuracytrain:',(b11+b22+b33)/(b11+b12+b13+b21+b22+b23+b31+b32+b33))

[222   0   5] 
 [  0 195   5] 
 [  2   3 199] 

[484   0   0] 
 [  0 517   0] 
 [  0   0 499] 

accuracytest: 0.9762282091917591
accuracytrain: 1.0


In [0]:
clf = RandomForestClassifier(n_estimators=250, max_depth=60,random_state=1)
clf.fit(xtrain, ytrain)
xdata1=clf.predict(xtest)
xdata2=clf.predict(xtrain)
p,r=confusion_matrix(xdata1,ytest)
p1,r1=confusion_matrix(xdata2,ytrain)
tp,fp=p
fn,tn=r

tp1,fp1=p1
fn1,tn1=r1
print(p,'\n',r,'\n')
print(p1,'\n',r1,'\n')
print('accuracytrain:',(tp+tn)/(tp+fp+fn+tn))
print('accuracytest:',(tp1+tn1)/(tp1+fp1+fn1+tn1))
